#!/usr/bin/env node
let fs = require('fs')
let path = require('path')

let componentName = process.argv[2]
const COMPONENT_PATH = path.resolve(__dirname, './src/components')
const STYLE_PATH = path.resolve(__dirname, './src/styles')
const DEMO_PATH = path.resolve(__dirname, './example')

//  create component dir
fs.mkdir(`${COMPONENT_PATH}/${componentName}`, err => {
  if (err) {
    return console.error(err)
  }
  console.log(`组件 "${componentName}" 目录创建成功!`)
})

let componentFileNames = [
  'index.js',
  `${componentName}.vue`
]

//  create component basic file
componentFileNames.forEach((filename) => {
  fs.open(`${COMPONENT_PATH}/${componentName}/${filename}`, 'w+', (err, fd) => {
    if (err) {
      return console.error(err)
    }
    console.log(`创建 "${COMPONENT_PATH}/${componentName}/${filename}" 成功!`)
  })
})

//  create example basic file
fs.open(`${DEMO_PATH}/pages/${componentName}.vue`, 'w+', (err, fd) => {
  if (err) {
    return console.error(err)
  }
  console.log(`创建 "${DEMO_PATH}/pages/${componentName}.vue" 成功!`)
})

//  create style basic file
fs.open(`${STYLE_PATH}/${componentName}.scss`, 'w+', (err, fd) => {
  if (err) {
    return console.error(err)
  }
  console.log(`创建 "${STYLE_PATH}/${componentName}.scss" 成功!`)

  fs.appendFile(`${STYLE_PATH}/index.scss`, `@import "${componentName}";\n`, err => {
    if (err) {
      return console.error(err)
    }
  })
})
